#!/usr/bin/env python3
#
# SPDX-License-Identifier: GPL-2.0-only

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), 'lib'))

from runqemu_utils import extract_sdk_main


sys.exit(extract_sdk_main())
